/**
 * Canonical clave de acceso fixtures used by the unit + property tests.
 *
 * Each fixture is a `(input, expected)` pair. The `expected` 49-digit string
 * was computed offline by running the reference module-11 algorithm published
 * in [`docs/sri-facturacion-electronica-ecuador.md`][docs] §4 on the same
 * input, then pinned here so any future drift in the implementation is
 * caught by a fast, deterministic comparison.
 *
 * The fixtures cover:
 *   - all five supported `codDoc` values (factura 01, NC 04, ND 05,
 *     guía 06, retención 07),
 *   - both `ambiente` values (1, 2),
 *   - both possible `secuencial` boundaries (`000000001`, `999999999`),
 *   - the special-case branches of módulo 11 (`r=10` → "1", `r=11` → "0").
 *
 * Source attribution:
 *   - algorithm definition: [docs] §4 ("Algoritmo del dígito verificador
 *     — Módulo 11"). The reference JS implementation in that section was
 *     re-executed locally to derive each `expected` clave.
 *   - field layout: [docs] §4 composition table + SPEC-0022 §1.
 *
 * [docs]: ../../../../docs/sri-facturacion-electronica-ecuador.md
 */
import type { BuildClaveAccesoInput } from "./clave-acceso.js";

export interface ClaveAccesoFixture {
  /** Short label for the test report. */
  readonly name: string;
  /** Original docs section this fixture lines up against. */
  readonly source: string;
  /** Input passed to {@link buildClaveAcceso}. */
  readonly input: BuildClaveAccesoInput;
  /** Pinned 49-digit clave de acceso. */
  readonly expected: string;
  /** Pinned módulo-11 check digit (the 49th char of `expected`). */
  readonly checkDigit: string;
}

/**
 * Five known-good fixtures spanning factura / NC / ND / guía / retención.
 * Each `expected` value was generated by running the algorithm in
 * docs/sri-facturacion-electronica-ecuador.md §4 on the corresponding
 * input — never hand-computed.
 */
export const CLAVE_FIXTURES: readonly ClaveAccesoFixture[] = [
  {
    name: "factura (codDoc=01, ambiente=1)",
    source: "docs/sri-facturacion-electronica-ecuador.md §4",
    input: {
      fechaEmision: "2026-05-19",
      codDoc: "01",
      ruc: "1790012345001",
      ambiente: "1",
      estab: "001",
      ptoEmi: "001",
      secuencial: "000000123",
      codigoNumerico: "12345678",
      tipoEmision: "1",
    },
    expected: "1905202601179001234500110010010000001231234567817",
    checkDigit: "7",
  },
  {
    name: "nota credito (codDoc=04, ambiente=2)",
    source: "docs/sri-facturacion-electronica-ecuador.md §4",
    input: {
      fechaEmision: "2026-06-01",
      codDoc: "04",
      ruc: "0992301234001",
      ambiente: "2",
      estab: "002",
      ptoEmi: "003",
      secuencial: "000000007",
      codigoNumerico: "87654321",
      tipoEmision: "1",
    },
    expected: "0106202604099230123400120020030000000078765432111",
    checkDigit: "1",
  },
  {
    name: "nota debito (codDoc=05, codigoNumerico=00000001)",
    source: "docs/sri-facturacion-electronica-ecuador.md §4",
    input: {
      fechaEmision: "2026-12-15",
      codDoc: "05",
      ruc: "1791234567001",
      ambiente: "1",
      estab: "001",
      ptoEmi: "001",
      secuencial: "000000999",
      codigoNumerico: "00000001",
      tipoEmision: "1",
    },
    expected: "1512202605179123456700110010010000009990000000119",
    checkDigit: "9",
  },
  {
    name: "guia (codDoc=06, secuencial=999999999, ambiente=2)",
    source: "docs/sri-facturacion-electronica-ecuador.md §4",
    input: {
      fechaEmision: "2027-01-31",
      codDoc: "06",
      ruc: "1790000000001",
      ambiente: "2",
      estab: "010",
      ptoEmi: "020",
      secuencial: "999999999",
      codigoNumerico: "99999999",
      tipoEmision: "1",
    },
    expected: "3101202706179000000000120100209999999999999999916",
    checkDigit: "6",
  },
  {
    name: "retencion (codDoc=07, secuencial=000000001)",
    source: "docs/sri-facturacion-electronica-ecuador.md §4",
    input: {
      fechaEmision: "2026-07-07",
      codDoc: "07",
      ruc: "0900000001001",
      ambiente: "1",
      estab: "001",
      ptoEmi: "001",
      secuencial: "000000001",
      codigoNumerico: "00000000",
      tipoEmision: "1",
    },
    expected: "0707202607090000000100110010010000000010000000011",
    checkDigit: "1",
  },
] as const;

/**
 * Special-case fixtures for the two módulo-11 branches that are otherwise
 * unreachable from random data: `r=11 → "0"` and `r=10 → "1"`.
 *
 * Each entry's `expected` was derived the same way as `CLAVE_FIXTURES`.
 */
export const CLAVE_SPECIAL_CASES: readonly {
  readonly name: string;
  readonly input: BuildClaveAccesoInput;
  readonly expected: string;
  readonly checkDigit: "0" | "1";
}[] = [
  {
    name: "r=11 → check digit '0' (sum mod 11 === 0)",
    input: {
      fechaEmision: "2026-05-19",
      codDoc: "01",
      ruc: "1790012345001",
      ambiente: "1",
      estab: "001",
      ptoEmi: "001",
      secuencial: "000000123",
      codigoNumerico: "00000003",
      tipoEmision: "1",
    },
    expected: "1905202601179001234500110010010000001230000000310",
    checkDigit: "0",
  },
  {
    name: "r=10 → check digit '1' (sum mod 11 === 1)",
    input: {
      fechaEmision: "2026-05-19",
      codDoc: "01",
      ruc: "1790012345001",
      ambiente: "1",
      estab: "001",
      ptoEmi: "001",
      secuencial: "000000123",
      codigoNumerico: "00000007",
      tipoEmision: "1",
    },
    expected: "1905202601179001234500110010010000001230000000711",
    checkDigit: "1",
  },
] as const;
